pipeline:
  build:
    image: computersciencehouse/bingehack4:latest
    commands:
    # set lang for unicode support
      - export LC_ALL=C.UTF-8
    # bingehack build
      - ./travis-build

# We still need this matrix to match what versions are listed in the Dockerfile.
# That way we can still test against different compiler versions

matrix:
  include:
    - CC: gcc-4.6
      CXX: g++-4.6
    - CC: gcc-4.7
      CXX: g++-4.7
    - CC: gcc-4.8
      CXX: g++-4.8
    - CC: clang-3.4
      CXX: clang-3.4
    - CC: clang-3.5
      CXX: clang-3.5
