pipeline:
  build:
    image: ubuntu:14.04
    commands:
    # set lang for unicode support
      - export LC_ALL=C.UTF-8
    # bingehack prep
      - apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 16126D3A3E5C1192
      - apt-get update -qq
      - apt-get install -qq g++ gcc flex bison libbison-dev libjansson-dev postgresql-client libpq-dev libsdl2-dev libpng-dev
    # bingehack build
      - ./travis-build
