install:
    - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 16126D3A3E5C1192
    - sudo apt-get update -qq
    - sudo apt-get install -qq libjansson-dev postgresql-client
language: c
script: ./travis-build
compiler:
    - clang
    - gcc
env:
    - CFLAGS="-O3"
    -
notifications:
    email:
        - bingehack-ci@csh.rit.edu
