install:
    - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 16126D3A3E5C1192
    - sudo apt-get update -qq
    - sudo apt-get install -qq libjansson-dev postgresql-client
language: c
script: mkdir build && cd build && cmake .. && make
compiler:
    - clang
    - gcc
